# Stage 1: Build
FROM node:slim AS build

# Set working directory inside the container
WORKDIR /app

# Declare build arguments
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_WS_BASE_URL

# Set environment variables for the build
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_WS_BASE_URL=$NEXT_PUBLIC_WS_BASE_URL

# Copy package.json and package-lock.json (if exists)
COPY package.json package-lock.json* ./ 

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production
FROM node:slim

# Set working directory
WORKDIR /app

# Copy build output and necessary files from the builder stage
COPY --from=build /app/.next ./.next
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/public ./public

# Install only production dependencies
RUN npm install --production

# Expose the desired port
EXPOSE 3002

# Start the application
CMD ["npm", "start"]
