version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - timescale-data:/var/lib/postgresql/datas
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default

  frontend:
    build:
      context: ../frontend
      dockerfile: DOCKERFILE
      args:
        NEXT_PUBLIC_BASE_URL: 'http://localhost:3000/api/v1'
        NEXT_PUBLIC_WS_BASE_URL: 'ws://localhost:3001'
    container_name: frontend
    ports:
      - "3002:3002"
    environment:
      NEXT_PUBLIC_BASE_URL: 'http://localhost:3000/api/v1'
      NEXT_PUBLIC_WS_BASE_URL: 'ws://localhost:3001'
    depends_on:
      - api
    networks:
      - default

  api:
    build:
      context: ../api
      dockerfile: DOCKERFILE
    container_name: api
    ports:
      - "3000:3000"
    environment:
      ALLOWED_BASE_URL: 'http://frontend:3002'
      PORT: 3000
      REDIS_DOMAIN: redis
      REDIS_PORT: 6379
      PG_USER: your_user
      HOST: timescaledb
      DATABASE: my_database
      PASSWORD: your_password
      PG_PORT: 5432
    depends_on:
      - redis
      - timescaledb
    networks:
      - default

  engine:
    build:
      context: ../engine
      dockerfile: DOCKERFILE
    container_name: engine
    environment:
      REDIS_DOMAIN: redis
      REDIS_PORT: 6379
    depends_on:
      - api
    networks:
      - default

  ws:
    build:
      context: ../ws
      dockerfile: DOCKERFILE
    container_name: ws
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      REDIS_DOMAIN: redis
      REDIS_PORT: 6379
    depends_on:
      - api
    networks:
      - default
  
  db:
    build: 
      context: ../db
      dockerfile: DOCKERFILE
    container_name: db
    environment:
      PG_USER: your_user
      HOST: timescaledb
      DATABASE: my_database
      PASSWORD: your_password
      PORT: 5432
      REDIS_DOMAIN: 'redis'
      REDIS_PORT: 6379
    depends_on:
      - api
    networks:
      - default

networks:
  default:
    name: shared-network

volumes:
  timescale-data:
